language: go
go: 1.8.x
services: docker
sudo: required
script: travis/install.sh
deploy:
- provider: script
  on: { branch: master }
  script: travis/deploy-to-dockerhub.sh
- provider: script
  on: { tags: true }
  script: travis/deploy-to-dockerhub.sh
- provider: releases
  api_key:
    secure: CAVhHMmVSg3UUpzpIHRN4vLQkIuJUf0LrqkLe8rq1DzlnxPoneobdjRWVybnHFwlPCmy5J/NtLGhqBIk0onhvPUXqzDGmKq2rb3vNZNqBA5X8ulU5tbidxpqDBgjMciCO89M8OgnK88z5V8n/22nG7kLpFm9tKXkN58sDT5lLgx1etYzXt+DFgaYakbsCeeCZ8ygngouAaP4FfMAFhTkb3k44Hlb/uRyGZ9/taLdWn+hu5Q5OMskiLsUlHIpLRxYUr4uRjtAnb+4Ru+sEFuPHqfskHFZgJNnYYpFzQG1DHWAFE2eKMnFIMZNizDuVV5duGQFRaQufh5yAz0r/ag4Nk4KrD2LXv2omH5CWXWxCOOBnT7JobOiKU/iFcIP0EEbkO6TxEKz2E3KbXd49UbtZ3sa3/Xx91jJdA4Wgzb/XlBoyCG4w6HahRCz2PQTRV1LMEN8lAqOkCXhiCRnWBS0aLRC72Vik5HIfEeMmN4fea8LZK8IUltGbsQfQ9op4nTBOspX9i0sfkP5AGCZLTf2/CvjJT9FOuAXmS21wAEdqZH+/7xfCwSRxJd6AVQb8tT7N5XhrNc5PCg0qL9zDnuIIJAzLlLCpHY5Bv/oXJg/lDgJLCl+IA1mwAlzxv8Yy7DaaUCHaQhrguuwD5157ApG4cu9V6o6OKfb4pmDUnROIJA=
  on: { tags: true }
  skip_cleanup: true
  file: [ amqp-to-kafka-linux64, amqp-to-kafka-darwin64, amqp-to-kafka-windows64.exe ]
